apiVersion: apps/v1
kind: Deployment
metadata:
  name: weaviate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weaviate
  template:
    metadata:
      labels:
        app: weaviate
    spec:
      containers:
      - name: weaviate
        image: semitechnologies/weaviate:latest
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_URL
          value: "postgres://{{pg_user}}:{{pg_password}}@database-host:5432/database-name?sslmode=disable"
